//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeBuddy
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class recipeingredient
    {
        [Key]
        public int recipeId { get; set; }
        [Key]
        public int ingredientId { get; set; }
        public decimal quantity { get; set; }
        public string unit { get; set; }
    
        public virtual ingredient ingredient { get; set; }
        public virtual recipe recipe { get; set; }
    }
}
